version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: critical_blunder_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: critical_blunder
      MYSQL_USER: critical_user
      MYSQL_PASSWORD: critical_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    container_name: critical_blunder_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/critical_blunder?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=critical_user
      - SPRING_DATASOURCE_PASSWORD=critical_pass
      - CORS_ALLOWED_ORIGIN=http://localhost:81
      - CORS_ALLOWED_ORIGIN_LIST=http://localhost:3000,http://localhost:5173,http://127.0.0.1,http://localhost:81
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: critical_blunder_frontend
    ports:
      - "81:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306 
    ports:
      - "8081:80"
    depends_on:
      - mysql
